kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pamir-rolebinding
  namespace: default
subjects:
- kind: User
  name: pamir
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pamir-role
  apiGroup: rbac.authorization.k8s.io